name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0' # This SDK range is fine. Flutter generally recommends using the latest stable release.

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3 # Updated to a more recent stable version (from 2.2.0)
  image_picker: ^1.1.2       # <--- ADDED: Required for picking images (e.g., profile pictures)
  http: ^1.2.1               # Updated to a more recent stable version (from 1.1.0). Only keep this if you have other parts of your app that make web requests.
  cupertino_icons: ^1.0.6    # Updated to a more recent stable version (from 1.0.2)
  intl: ^0.19.0              # Updated to a more recent stable version (from 0.20.2 - 0.19.0 is newer). This is for internationalization, date formatting etc.
  table_calendar: ^3.1.1     # Updated to a more recent stable version (from 3.0.9)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0      # Updated to reflect common current version (from 5.0.0, which might be a typo or older lints)

# The flutter section should only appear ONCE. This is correct in your file.
flutter:
  uses-material-design: true

  # Declare your assets here, indented under 'flutter:'
  # If you want to include all files in the 'assets/' folder:
  assets:
    - assets/ # This is the most common and recommended way if you put all your images, fonts etc. into an 'assets' folder.
  # If you use 'assets/', ensure 'WhatsApp Image 2025-06-16 at 01.06.36.jpeg' and 'Screenshot 2025-06-16 114930.jpg'
  # are placed inside a folder named 'assets' at the root of your project (e.g., your_project/assets/image.jpeg).
