name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0' # Good, specifies SDK range

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0 # Used for local data storage in your app
  http: ^1.1.0 # Only keep this if you have other parts of your app that make web requests
  cupertino_icons: ^1.0.2 # If you are using Cupertino icons
  intl: ^0.20.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The flutter section should only appear ONCE.
flutter:
  uses-material-design: true

  # Declare your assets here, indented under 'flutter:'
  # If you want to include all files in the 'assets/' folder:
  assets:
    - assets/
  # Or if you want to be specific:
  # assets:
  #   - assets/WhatsApp Image 2025-06-16 at 01.06.36.jpeg
  #   - assets/logo.png # If you have both, list them or just use assets/