name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0' # Good, specifies SDK range

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.1
  image_picker: ^1.1.0
  http: ^0.13.6
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The flutter section is typically at the end
flutter:
  uses-material-design: true
